{
 "title": "Ceph OSD Information",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "percentile", "query": "95,96,97,98,99" },
   { "name": "max_devices", "query": "10" },
   {
    "name": "osd_id",
    "label": "OSD Id",
    "query": "label_values(ceph_osd_metadata, ceph_daemon)"
   },
   {
    "name": "bluestore_osd_id",
    "query": "label_values(ceph_bluefs_bytes_written_wal, ceph_daemon)"
   },
   {
    "name": "filestore_osd_id",
    "query": "label_values(ceph_filestore_journal_latency_count, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(max by (ceph_daemon) (ceph_osd_metadata))"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(ceph_osd_up > 0.5)" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_osd_up < 0.5)" }
   ]
  },
  {
   "title": "OSD Size",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(ceph_disk_occupation,\"ceph_osd\",\"$1\",\"ceph_daemon\",\"osd.(.*)\") * on(ceph_osd) group_right(instance,device) \nlabel_replace(ceph_osd_stat_bytes{ceph_daemon=~\"osd.[[osd_id]]\"},\"ceph_osd\",\"$1\",\"ceph_daemon\",\"osd.(.*)\")"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by(device_class) (ceph_osd_metadata)",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "grafana-piechart-panel",
   "description": "The pie chart shows the various OSD sizes used within the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes < 1099511627776)",
     "legendFormat": "<1 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes >= 13194139533312)",
     "legendFormat": "12TB+"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes)",
     "legendFormat": "bluestore"
    },
    {
     "expr": "count(ceph_osd_metadata) - count(ceph_bluefs_wal_total_bytes)",
     "legendFormat": "filestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes)*count(ceph_osd_metadata)",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "Filestore OSD Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
     "content": "<h1>Ceph Filestore I/O Process</h1>\n<p style=\"text-align: justify;\">\nA write request is first committed to a journal using direct-io (<i><b>apply</b></i>). Once this write is complete, the data is persisted to HDD by a second 'buffered' write operation (<i><b>commit</b></i>). The commit operation is basically a measure of time taken to perform a <i>syncfs</i> call to flush dirty pages to disk, and is therefore <b>not</b> a time associated with any specific client initiated operation.<p> The tables on the right show commit and apply latencies for all OSDs, or use the pull down above to focus on a specific OSD.\n"
    },
    {
     "type": "table",
     "description": "Filestore OSDs",
     "gridPos": { "h": 8, "w": 2, "x": 10, "y": 8 },
     "targets": [
      {
       "expr": "label_replace(\n  ceph_disk_occupation{ceph_daemon=~\"osd.($filestore_osd_id)\"},\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)",
       "legendFormat": "{{osd_num}}"
      }
     ]
    },
    {
     "type": "table",
     "description": "Apply latency covers the time taken to commit to the journal and complete the transaction",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "label_replace(\n  topk($max_devices,\n    ceph_osd_apply_latency_ms{ceph_daemon=~\"osd.[[osd_id]]\"} + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "type": "table",
     "description": "Commit latency is the time taken for writes to be flushed to disk as part of async kernel activity",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 8 },
     "targets": [
      {
       "expr": "label_replace(\n  topk($max_devices,\n    ceph_osd_commit_latency_ms{ceph_daemon=~\"osd.[[osd_id]]\"} + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n  )",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Filestore Latency for OSD '$osd_id'",
     "type": "graph",
     "description": "Shows the latency for a given OSD, allowing you to compare a specific OSD against the $percentile%ile graph. Note that when the \"OSD Id\" pull-down shows **ALL**, the graph will be empty to avoid the chart being unreadable.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(\n  ceph_osd_commit_latency_ms{ceph_daemon=~\"osd.([[osd_id]])\"} + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n)",
       "legendFormat": "commit"
      },
      {
       "expr": "avg(\n  ceph_osd_apply_latency_ms{ceph_daemon=~\"osd.([[osd_id]])\"} + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n)",
       "legendFormat": "apply"
      }
     ]
    },
    {
     "title": "Filestore IO Summary - all OSD's @ $percentile%ile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile(\n  $percentile/100,\n  ceph_osd_commit_latency_ms + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n)",
       "legendFormat": "commit"
      },
      {
       "expr": "quantile(\n  $percentile/100,\n  ceph_osd_apply_latency_ms + on (ceph_daemon) (ceph_filestore_journal_latency_count * 0)\n)",
       "legendFormat": "apply"
      },
      {
       "expr": "quantile(\n  $percentile/100,\n    rate(ceph_filestore_journal_latency_sum[$__interval]) / \n    (rate(ceph_filestore_journal_latency_count[$__interval]) != 0)\n)",
       "legendFormat": "journal"
      }
     ]
    }
   ]
  },
  {
   "title": "Bluestore OSD Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "content": "<h1>Ceph Bluestore I/O Process</h1>\n<p style=\"text-align: justify;\">\nUnlike filestore, bluestore does not suffer from a double-write penalty (i.e write to journal then write to HDD). With bluestore, once a write is scheduled (<b>submit</b> and <b>throttle</b> latencies), it is done directly to the disk (<b>AIO wait</b>), and then the metadata relating to the object is changed (<b>kv_commit</b>). Writes are not considered complete until the kv store is updated. <p> The tables on the right focus on  the top 10 Bluestore OSDs with the highest latencies.\n"
    },
    {
     "type": "table",
     "description": "Bluestore OSDs",
     "gridPos": { "h": 8, "w": 2, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(\n  ceph_disk_occupation{ceph_daemon=~\"osd.($bluestore_osd_id)\"},\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)",
       "legendFormat": "{{osd_num}}"
      }
     ]
    },
    {
     "type": "table",
     "description": "Time spent preparing the request (transaction)",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(\n  (\n    topk($max_devices,\n      rate(ceph_bluestore_submit_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n      (rate(ceph_bluestore_submit_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n    )\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)"
      }
     ]
    },
    {
     "type": "table",
     "description": "Time requests wait due to throttling or busy conditions",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(\n  (\n    topk($max_devices,\n      rate(ceph_bluestore_throttle_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n      (rate(ceph_bluestore_throttle_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n    )\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)"
      }
     ]
    },
    {
     "type": "table",
     "description": "Time spent waiting for the physical I/O request to complete",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(\n  (\n    topk($max_devices,\n      rate(ceph_bluestore_state_aio_wait_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n      (rate(ceph_bluestore_state_aio_wait_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n    )\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)"
      }
     ]
    },
    {
     "type": "table",
     "description": "Time spent waiting for rocksdb (metadata store) to commit meta data",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "targets": [
      {
       "expr": "label_replace(\n  (\n    topk($max_devices,\n      rate(ceph_bluestore_commit_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n      (rate(ceph_bluestore_commit_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n    )\n  ),\n  \"osd_num\",\n  \"$1\",\n  \"ceph_daemon\",\n  \"osd.(.*)\"\n)"
      }
     ]
    },
    {
     "title": "Bluestore Latency for OSD '$osd_id'",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(\n  rate(ceph_bluestore_submit_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n  (rate(ceph_bluestore_submit_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n)",
       "legendFormat": "Submit"
      },
      {
       "expr": "avg(\n  rate(ceph_bluestore_throttle_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n  (rate(ceph_bluestore_throttle_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n)",
       "legendFormat": "Throttle"
      },
      {
       "expr": "avg(\n  rate(ceph_bluestore_state_aio_wait_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n  (rate(ceph_bluestore_state_aio_wait_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n)",
       "legendFormat": "AIO Wait"
      },
      {
       "expr": "avg(\n    rate(ceph_bluestore_commit_lat_sum{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) / \n    (rate(ceph_bluestore_commit_lat_count{ceph_daemon=~\"osd.[[osd_id]]\"}[$__interval]) != 0)\n)",
       "legendFormat": "KV Commit"
      }
     ]
    },
    {
     "title": "BlueStore IO Summary - all OSD's @ $percentile%ile",
     "type": "graph",
     "description": "This charts shows the $percentile%ile latencies across all OSDs, which indicates overall performance, but does not represent any specific OSD",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile(\n  $percentile/100,\n    rate(ceph_bluestore_submit_lat_sum[$__interval]) / \n    (rate(ceph_bluestore_submit_lat_count[$__interval]) != 0)\n)",
       "legendFormat": "Submit"
      },
      {
       "expr": "quantile(\n  $percentile/100,\n    rate(ceph_bluestore_throttle_lat_sum[$__interval]) / \n    (rate(ceph_bluestore_throttle_lat_count[$__interval]) != 0)\n)",
       "legendFormat": "Throttle"
      },
      {
       "expr": "quantile(\n  $percentile/100,\n    rate(ceph_bluestore_state_aio_wait_lat_sum[$__interval]) / \n    (rate(ceph_bluestore_state_aio_wait_lat_count[$__interval]) != 0)\n)",
       "legendFormat": "AIO Wait"
      },
      {
       "expr": "quantile(\n  $percentile/100,\n    rate(ceph_bluestore_commit_lat_sum[$__interval]) / \n    (rate(ceph_bluestore_commit_lat_count[$__interval]) != 0)\n)",
       "legendFormat": "KV Commit"
      }
     ]
    }
   ]
  }
 ]
}