---
- name: Look for /etc/sysconfig and /etc/default
  stat:
    path: "/etc/{{ item }}/"
  with_items:
    - sysconfig
    - default
  register: stat

- name: Decide whether to use /etc/sysconfig or /etc/default
  set_fact:
    sysconfig_dir: "{{ item.item }}"
  with_items: "{{ stat.results }}"
  when: item.stat.exists

- name: Ship defaults file
  template:
    src: sysconfig
    dest: "/etc/{{ sysconfig_dir }}/{{ node_exporter.service_name }}"
    owner: root
    group: root
    mode: 0644

- name: Ship systemd service file
  template:
    src: node_exporter.service
    dest: '/etc/systemd/system/{{ node_exporter.service_name }}.service'
    owner: root
    group: root
    mode: 0644
  notify: "Restart service"
