---
- name: Add Grafana repo
  template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
  when:
    - ansible_pkg_mgr == 'yum'
    - use_epel
    - devel_mode

- name: Remove Grafana repo
  file:
    path: /etc/yum.repos.d/grafana.repo
    state: absent
  when:
    - ansible_pkg_mgr == "yum"
    - not use_epel
    - devel_mode

- name: Install grafana repo
  copy:
    src: files/grafana.list
    dest: /etc/apt/sources.list.d/grafana.list
  when:
    - ansible_pkg_mgr == "apt"
    - devel_mode

- name: Add packagecloud GPG key to apt
  apt_key:
    # This is the key used by the grafana repo
    url: https://packagecloud.io/gpg.key
    id: D59097AB
    state: present
  when:
    - ansible_pkg_mgr == "apt"
    - devel_mode

- name: Update apt cache
  apt:
    update_cache: true
  when:
    - ansible_pkg_mgr == 'apt'
    - devel_mode
