---
- name: Set collectd_dir
  set_fact:
    collectd_dir: "/usr/lib{{ '64' if ansible_pkg_mgr == 'yum' else '' }}/collectd"

- name: Set collectd_cephmetrics_dir
  set_fact:
    collectd_cephmetrics_dir: "{{ collectd_dir }}/cephmetrics"

- name: Remove stale Python files
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ collectd_cephmetrics_dir }}/cephmetrics.py"
    - "{{ collectd_cephmetrics_dir }}/cephmetrics.pyc"

- name: Ship collector plugins
  copy:
    src: files/cephmetrics
    dest: "{{ collectd_cephmetrics_dir }}"
  notify: Restart collectd
