global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ceph'
    honor_labels: true
    static_configs:
{% for host in groups['mgrs'] %}
      - targets: ['{{ host }}:9283']
        labels:
          instance: 'ceph_cluster'
{% endfor %}
  - job_name: 'node'
    static_configs:
{% for host in (groups['all'] | difference(groups['ceph-grafana'])) %}
      - targets: ['{{ host }}:9100']
        labels:
          instance: "{{ hostvars[host]['ansible_nodename'] }}"
{% endfor %}
  - job_name: 'cephmetrics'
    static_configs:
{% for host in groups['ceph-grafana'] %}
      - targets: ['{{ host }}:9100']
        labels:
          instance: "{{ hostvars[host]['ansible_nodename'] }}"
{% endfor %}
{% if 'iscsis' in groups %}
  - job_name: 'iscsi-gws'
    static_configs:
{% for host in groups['iscsis'] %}
      - targets: ['{{ host }}:9287']
        labels:
          instance: "{{ hostvars[host]['ansible_nodename'] }}"
{% endfor %}
{% endif %}
